"""empty message

Revision ID: 15633de31fa8
Revises: f250474af8f0
Create Date: 2023-11-03 01:34:54.437123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15633de31fa8'
down_revision = 'f250474af8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])
        batch_op.drop_column('active_user')
        batch_op.drop_column('active_contractor')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_constraint('contract_ibfk_1', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('contract_ibfk_1', 'service', ['service_id'], ['id'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_contractor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active_user', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
