"""empty message

Revision ID: 2a10cc8a4730
Revises: e3c7024f576c
Create Date: 2023-10-28 10:02:12.867625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a10cc8a4730'
down_revision = 'e3c7024f576c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_review', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.ENUM('1', '2', '3', '4', '5'),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_review', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('1', '2', '3', '4', '5'),
               existing_nullable=True)

    # ### end Alembic commands ###
