"""empty message

Revision ID: 4af9ba255df6
Revises: 2a10cc8a4730
Create Date: 2023-10-28 10:48:02.171283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af9ba255df6'
down_revision = '2a10cc8a4730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_constraint('portfolio_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contractor', ['contractor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('portfolio_ibfk_1', 'contractor', ['contractor_id'], ['id'])

    # ### end Alembic commands ###
