"""Convert Base model to an abstract model

Revision ID: 79b6cf6ed167
Revises: 6744db7cf2d5
Create Date: 2023-10-26 02:46:17.719343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b6cf6ed167'
down_revision = '6744db7cf2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###
