"""empty message

Revision ID: 8ca60a732084
Revises: b0c0e2e89b2f
Create Date: 2023-10-28 11:01:41.717355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ca60a732084'
down_revision = 'b0c0e2e89b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
