"""empty message

Revision ID: 998cf4329b6a
Revises: dda2a5e56254
Create Date: 2023-10-28 11:55:37.758371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '998cf4329b6a'
down_revision = 'dda2a5e56254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
