"""empty message

Revision ID: b0c0e2e89b2f
Revises: 4af9ba255df6
Create Date: 2023-10-28 10:52:49.254838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0c0e2e89b2f'
down_revision = '4af9ba255df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
